- name: kalliope dreambox neuron install
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Install pip dependencies"
      pip:
        name: dreambox
        version: 0.0.3
